package muargus.view;

import java.awt.Frame;
import javax.swing.JOptionPane;
import muargus.model.Combinations;

/**
 *
 * @author Statistics Netherlands
 */
public class GenerateAutomaticTables extends DialogBase {

    private final Combinations model;
    private boolean valid; // is used to continue with the calculation
    private final Frame parent;
    private final int numberOfVariables;

    /**
     * Creates new form GenerateAutomaticTables
     *
     * @param parent the Frame of the mainFrame.
     * @param modal boolean to set the modal status
     * @param model
     * @param numberOfVariables
     */
    public GenerateAutomaticTables(java.awt.Frame parent, boolean modal, Combinations model,
            int numberOfVariables) {
        super(parent, modal, null);
        this.model = model;
        this.valid = false;
        this.parent = parent;
        this.numberOfVariables = numberOfVariables;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Method for generating tables");
    }

    public int getDimensionTextField() {
        return Integer.parseInt(dimensionTextField.getText());
    }

    public boolean isMakeUpToDimensionRadioButton() {
        return makeUpToDimensionRadioButton.isSelected();
    }

    public boolean isUseIdentificatinLevelRadioButton() {
        return useIdentificatinLevelRadioButton.isSelected();
    }

    public boolean isValid() {
        return this.valid;
    }

    public void setValid(boolean valid) {
        this.valid = valid;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        methodButtonGroup = new javax.swing.ButtonGroup();
        methodPanel = new javax.swing.JPanel();
        useIdentificatinLevelRadioButton = new javax.swing.JRadioButton();
        makeUpToDimensionRadioButton = new javax.swing.JRadioButton();
        dimensionTextField = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Generate");

        methodPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Method"));

        methodButtonGroup.add(useIdentificatinLevelRadioButton);
        useIdentificatinLevelRadioButton.setSelected(true);
        useIdentificatinLevelRadioButton.setText("Use identification level");
        useIdentificatinLevelRadioButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                useIdentificatinLevelRadioButtonStateChanged(evt);
            }
        });

        methodButtonGroup.add(makeUpToDimensionRadioButton);
        makeUpToDimensionRadioButton.setText("Make all tables up to dimension");

        dimensionTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dimensionTextFieldFocusGained(evt);
            }
        });

        javax.swing.GroupLayout methodPanelLayout = new javax.swing.GroupLayout(methodPanel);
        methodPanel.setLayout(methodPanelLayout);
        methodPanelLayout.setHorizontalGroup(
            methodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(methodPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(methodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(methodPanelLayout.createSequentialGroup()
                        .addComponent(useIdentificatinLevelRadioButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(methodPanelLayout.createSequentialGroup()
                        .addComponent(makeUpToDimensionRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dimensionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        methodPanelLayout.setVerticalGroup(
            methodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(methodPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(useIdentificatinLevelRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(methodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(makeUpToDimensionRadioButton)
                    .addComponent(dimensionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(methodPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(methodPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.setValid(false);
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        this.setValid(true);
        int dimensions = 0;
        if (makeUpToDimensionRadioButton.isSelected()) {
            try {
                dimensions = Integer.parseInt(dimensionTextField.getText());

                if (dimensions <= 0) {
                    JOptionPane.showMessageDialog(this, "Illegal value for the dimension, dimension cannot be smaller than 1");
                    this.setValid(false);
                } else if (dimensions > this.numberOfVariables) {
                    JOptionPane.showMessageDialog(this, "Not enough identifying variables for this request");
                    this.setValid(false);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Illegal value for the dimension, please enter a positive integer");
                this.setValid(false);
            }
        }

        if (isValid()) {
            this.setValid(false);
            if (useIdentificatinLevelRadioButton.isSelected()) {
                ArgusInput getThreshold = new ArgusInput(parent, true, this.model, true);
                getThreshold.setLabelText("Threshold");
                getThreshold.setTitle("Threshold");
                getThreshold.setVisible(true);
                if (getThreshold.isThresholdValid() && getThreshold.isOkButtonPressed()) {
                    model.setThreshold(getThreshold.getTextField());
                    this.setValid(true);
                }
            } else if (makeUpToDimensionRadioButton.isSelected()) {
                int[] thresholds = model.getThresholds();
                for (int i = 0; i < dimensions; i++) {
                    this.setValid(false);
                    ArgusInput getThreshold = new ArgusInput(parent, true, this.model, true);
                    getThreshold.setLabelText("Threshold for dim" + (i + 1));
                    getThreshold.setTitle("Threshold");
                    getThreshold.setTextField(Integer.toString(thresholds[i]));
                    if (i > 0) {
                        getThreshold.setPreviousThreshold(thresholds[i - 1]);
                        if (thresholds[i] < thresholds[i - 1]) {
                            getThreshold.setTextField(Integer.toString(thresholds[i - 1]));
                        }
                    }
                    getThreshold.setVisible(true);
                    if (getThreshold.isThresholdValid() && getThreshold.isOkButtonPressed()) {
                        thresholds[i] = Integer.parseInt(getThreshold.getTextField());
                        this.setValid(true);
                    }
                }
                model.setThresholds(thresholds);
                model.setThreshold(thresholds[0]);
            }
        }

        if (isValid()) {
            this.setVisible(false);
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void dimensionTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dimensionTextFieldFocusGained
        makeUpToDimensionRadioButton.setSelected(true);
    }//GEN-LAST:event_dimensionTextFieldFocusGained

    private void useIdentificatinLevelRadioButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_useIdentificatinLevelRadioButtonStateChanged
        if (useIdentificatinLevelRadioButton.isSelected()) {
            dimensionTextField.setText("");
        }
    }//GEN-LAST:event_useIdentificatinLevelRadioButtonStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField dimensionTextField;
    private javax.swing.JRadioButton makeUpToDimensionRadioButton;
    private javax.swing.ButtonGroup methodButtonGroup;
    private javax.swing.JPanel methodPanel;
    private javax.swing.JButton okButton;
    private javax.swing.JRadioButton useIdentificatinLevelRadioButton;
    // End of variables declaration//GEN-END:variables
}
