/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package muargus.view;

import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import muargus.controller.GlobalRecodeController;
import muargus.model.GlobalRecodeModel;
import muargus.model.MetadataMu;
import muargus.model.RecodeMu;
import muargus.model.VariableMu;

/**
 *
 * @author ambargus
 */
public class GlobalRecodeView extends javax.swing.JDialog {

    GlobalRecodeController controller;
    GlobalRecodeModel model;
    private MetadataMu metadataMu;  // ik weet niet of we die hier nodig hebben, maar voor de zekerheid heb ik hem er bij gezet
    private String[][] data;
    private TableModel tableModel;

    /**
     * Creates new form GlobalRecodeView
     *
     * @param parent
     * @param modal
     * @param controller
     */
    public GlobalRecodeView(java.awt.Frame parent, boolean modal, GlobalRecodeController controller) {
        super(parent, modal);
        initComponents();
        this.controller = controller;
        this.model = this.controller.getModel();
        this.setLocationRelativeTo(null);
        this.variablesTable.getSelectionModel().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }

    public void setMetadataMu(MetadataMu metadataMu) {
        this.metadataMu = metadataMu;
        makeVariables();
    }

    public void makeVariables() {
        this.model.clearRecodeMus();
        for (VariableMu v : this.model.getVariables()) {
            RecodeMu recodeMu = new RecodeMu(v);
            this.model.addRecodeMu(recodeMu);
        }

        
        this.data = new String[this.model.getRecodeMus().size()][2];
        this.updateTable();
        this.variablesTable.getSelectionModel().setSelectionInterval(0, 0);
        
        this.variablesTable.getColumnModel().getColumn(0).setMinWidth(30);
        this.variablesTable.getColumnModel().getColumn(0).setPreferredWidth(30);
        this.variablesTable.getColumnModel().getColumn(1).setMinWidth(70);
        this.variablesTable.getColumnModel().getColumn(1).setPreferredWidth(70);

        updateValues();
    }

    public void updateTable() {
        int index = 0;
        for (RecodeMu r : model.getRecodeMus()) {
            data[index] = r.getTableRow();
            index++;
        }

        this.tableModel = new DefaultTableModel(data, this.model.getColumnNames());
        this.variablesTable.setModel(this.tableModel);
    }

    public void updateValues() {
        //this.updateTable();
        //System.out.println(variablesTable.getSelectedRow());
        //this.variablesTable.getSelectionModel().setSelectionInterval(variablesTable.getSelectedRow(), variablesTable.getSelectedRow());

        RecodeMu selected = this.getSelectedVariable();
        this.missing_1_originalTextField.setText(selected.getMissing_1_original());
        this.missing_2_originalTextField.setText(selected.getMissing_2_original());
        this.truncateButton.setEnabled(selected.getVariable().isTruncable());
        this.applyButton.setEnabled(selected.isRead());
        this.undoButton.setEnabled(selected.isRecoded());
    }

    private RecodeMu getSelectedVariable() {
        RecodeMu selected = model.getRecodeMus().get(variablesTable.getSelectedRow());
        return selected;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        variablesScrollPane = new javax.swing.JScrollPane();
        variablesTable = new javax.swing.JTable();
        editLabel = new javax.swing.JLabel();
        editScrollPane = new javax.swing.JScrollPane();
        editTextField = new javax.swing.JTextField();
        codelistRecodeLabel = new javax.swing.JLabel();
        codelistRecodeTextField = new javax.swing.JTextField();
        codelistRecodeButton = new javax.swing.JButton();
        globalRecodeRecodeTextField = new javax.swing.JTextField();
        globalRecodeRecodeButton = new javax.swing.JButton();
        warningLabel = new javax.swing.JLabel();
        warningScrollPane = new javax.swing.JScrollPane();
        warningTextArea = new javax.swing.JTextArea();
        midSectionPanel = new javax.swing.JPanel();
        buttonPanel = new javax.swing.JPanel();
        readButton = new javax.swing.JButton();
        applyButton = new javax.swing.JButton();
        truncateButton = new javax.swing.JButton();
        undoButton = new javax.swing.JButton();
        missingValuesPanel = new javax.swing.JPanel();
        originalValuesLabel = new javax.swing.JLabel();
        missing_1_originalLabel = new javax.swing.JLabel();
        missing_1_originalTextField = new javax.swing.JTextField();
        missing_2_originalLabel = new javax.swing.JLabel();
        missing_2_originalTextField = new javax.swing.JTextField();
        valuesAfterRecoding = new javax.swing.JLabel();
        mising_1_newLabel = new javax.swing.JLabel();
        missing_1_newTextField = new javax.swing.JTextField();
        missing_2_newLabel = new javax.swing.JLabel();
        missing_2_newTextField = new javax.swing.JTextField();
        closePanel = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();
        codelistRecodeLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Global Recode");

        variablesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "R", "Variable"
            }
        ));
        variablesTable.setDragEnabled(true);
        variablesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                variablesTableMouseClicked(evt);
            }
        });
        variablesTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                variablesTableKeyReleased(evt);
            }
        });
        variablesScrollPane.setViewportView(variablesTable);
        if (variablesTable.getColumnModel().getColumnCount() > 0) {
            variablesTable.getColumnModel().getColumn(0).setPreferredWidth(6);
        }

        editLabel.setText("Edit box for global recode");

        editScrollPane.setViewportView(editTextField);

        codelistRecodeLabel.setText("Codelist for recode");

        codelistRecodeButton.setText("...");
        codelistRecodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codelistRecodeButtonActionPerformed(evt);
            }
        });

        globalRecodeRecodeButton.setText("...");
        globalRecodeRecodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                globalRecodeRecodeButtonActionPerformed(evt);
            }
        });

        warningLabel.setText("Warning");

        warningTextArea.setBackground(new java.awt.Color(200, 200, 200));
        warningTextArea.setColumns(20);
        warningTextArea.setRows(5);
        warningScrollPane.setViewportView(warningTextArea);

        buttonPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        readButton.setText("Read");
        readButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readButtonActionPerformed(evt);
            }
        });

        applyButton.setText("Apply");
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButtonActionPerformed(evt);
            }
        });

        truncateButton.setText("Truncate");
        truncateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                truncateButtonActionPerformed(evt);
            }
        });

        undoButton.setText("Undo");
        undoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(readButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(applyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(truncateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(undoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(readButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(applyButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(truncateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(undoButton)
                .addContainerGap())
        );

        missingValuesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Missing Values"));

        originalValuesLabel.setText("Original values");

        missing_1_originalLabel.setText("1");

        missing_1_originalTextField.setEditable(false);

        missing_2_originalLabel.setText("2");

        missing_2_originalTextField.setEditable(false);

        valuesAfterRecoding.setText("Values after recoding");

        mising_1_newLabel.setText("1");

        missing_2_newLabel.setText("2");

        javax.swing.GroupLayout missingValuesPanelLayout = new javax.swing.GroupLayout(missingValuesPanel);
        missingValuesPanel.setLayout(missingValuesPanelLayout);
        missingValuesPanelLayout.setHorizontalGroup(
            missingValuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(missingValuesPanelLayout.createSequentialGroup()
                .addGroup(missingValuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(missingValuesPanelLayout.createSequentialGroup()
                        .addGroup(missingValuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(missing_2_originalLabel)
                            .addComponent(missing_1_originalLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(missingValuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(missing_1_originalTextField)
                            .addComponent(missing_2_originalTextField)))
                    .addGroup(missingValuesPanelLayout.createSequentialGroup()
                        .addComponent(mising_1_newLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(missing_1_newTextField))
                    .addGroup(missingValuesPanelLayout.createSequentialGroup()
                        .addComponent(originalValuesLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(missingValuesPanelLayout.createSequentialGroup()
                        .addComponent(missing_2_newLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(missing_2_newTextField))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, missingValuesPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(valuesAfterRecoding)))
                .addContainerGap())
        );
        missingValuesPanelLayout.setVerticalGroup(
            missingValuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(missingValuesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(originalValuesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(missingValuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(missing_1_originalLabel)
                    .addComponent(missing_1_originalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(missingValuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(missing_2_originalLabel)
                    .addComponent(missing_2_originalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(valuesAfterRecoding)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(missingValuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(missing_1_newTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mising_1_newLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(missingValuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(missing_2_newTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(missing_2_newLabel))
                .addContainerGap())
        );

        closePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout closePanelLayout = new javax.swing.GroupLayout(closePanel);
        closePanel.setLayout(closePanelLayout);
        closePanelLayout.setHorizontalGroup(
            closePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(closePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(closeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        closePanelLayout.setVerticalGroup(
            closePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(closePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(closeButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout midSectionPanelLayout = new javax.swing.GroupLayout(midSectionPanel);
        midSectionPanel.setLayout(midSectionPanelLayout);
        midSectionPanelLayout.setHorizontalGroup(
            midSectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, midSectionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(midSectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(closePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(missingValuesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        midSectionPanelLayout.setVerticalGroup(
            midSectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(midSectionPanelLayout.createSequentialGroup()
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(missingValuesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        codelistRecodeLabel1.setText("Global recode file");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(variablesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(midSectionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editScrollPane)
                    .addComponent(warningScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(warningLabel)
                            .addComponent(editLabel)
                            .addComponent(codelistRecodeLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(codelistRecodeTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codelistRecodeButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(codelistRecodeLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(globalRecodeRecodeTextField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(globalRecodeRecodeButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(midSectionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(variablesScrollPane)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(editLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(codelistRecodeLabel)
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(codelistRecodeButton)
                                    .addComponent(codelistRecodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(codelistRecodeLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(globalRecodeRecodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(globalRecodeRecodeButton))
                                .addGap(18, 18, 18)
                                .addComponent(warningLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(warningScrollPane)))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        controller.close();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void codelistRecodeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codelistRecodeButtonActionPerformed
        controller.codelistRecode();
    }//GEN-LAST:event_codelistRecodeButtonActionPerformed

    private void truncateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_truncateButtonActionPerformed
        this.getSelectedVariable().setTruncated(!this.getSelectedVariable().isTruncated());
        updateValues();
        controller.truncate();
    }//GEN-LAST:event_truncateButtonActionPerformed

    private void readButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readButtonActionPerformed
        this.getSelectedVariable().setRead(!this.getSelectedVariable().isRead());
        updateValues();
        controller.read();
    }//GEN-LAST:event_readButtonActionPerformed

    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
        controller.apply();
    }//GEN-LAST:event_applyButtonActionPerformed

    private void undoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoButtonActionPerformed
        controller.undo();
    }//GEN-LAST:event_undoButtonActionPerformed

    private void globalRecodeRecodeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_globalRecodeRecodeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_globalRecodeRecodeButtonActionPerformed

    private void variablesTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_variablesTableMouseClicked

        updateValues();
    }//GEN-LAST:event_variablesTableMouseClicked

    private void variablesTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_variablesTableKeyReleased
        // TODO add your handling code here:
        updateValues();
    }//GEN-LAST:event_variablesTableKeyReleased

    /**
     *
     * @param filename
     */
    public void setCodelistText(String filename) {
        codelistRecodeTextField.setText(filename);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyButton;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton closeButton;
    private javax.swing.JPanel closePanel;
    private javax.swing.JButton codelistRecodeButton;
    private javax.swing.JLabel codelistRecodeLabel;
    private javax.swing.JLabel codelistRecodeLabel1;
    private javax.swing.JTextField codelistRecodeTextField;
    private javax.swing.JLabel editLabel;
    private javax.swing.JScrollPane editScrollPane;
    private javax.swing.JTextField editTextField;
    private javax.swing.JButton globalRecodeRecodeButton;
    private javax.swing.JTextField globalRecodeRecodeTextField;
    private javax.swing.JPanel midSectionPanel;
    private javax.swing.JLabel mising_1_newLabel;
    private javax.swing.JPanel missingValuesPanel;
    private javax.swing.JTextField missing_1_newTextField;
    private javax.swing.JLabel missing_1_originalLabel;
    private javax.swing.JTextField missing_1_originalTextField;
    private javax.swing.JLabel missing_2_newLabel;
    private javax.swing.JTextField missing_2_newTextField;
    private javax.swing.JLabel missing_2_originalLabel;
    private javax.swing.JTextField missing_2_originalTextField;
    private javax.swing.JLabel originalValuesLabel;
    private javax.swing.JButton readButton;
    private javax.swing.JButton truncateButton;
    private javax.swing.JButton undoButton;
    private javax.swing.JLabel valuesAfterRecoding;
    private javax.swing.JScrollPane variablesScrollPane;
    private javax.swing.JTable variablesTable;
    private javax.swing.JLabel warningLabel;
    private javax.swing.JScrollPane warningScrollPane;
    private javax.swing.JTextArea warningTextArea;
    // End of variables declaration//GEN-END:variables

}
