/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package muargus.view;

import muargus.controller.MakeProtectedFileController;

/**
 *
 * @author ambargus
 */
public class MakeProtectedFileView extends javax.swing.JDialog {
    
    MakeProtectedFileController controller;

    /**
     * Creates new form MakeProtectedFileView
     */
    public MakeProtectedFileView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        controller = new MakeProtectedFileController(this);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        suppressionButtonGroup = new javax.swing.ButtonGroup();
        hhIdentifierButtonGroup = new javax.swing.ButtonGroup();
        suppressionPanel = new javax.swing.JPanel();
        noSuppressionRadioButton = new javax.swing.JRadioButton();
        useWeightRadioButton = new javax.swing.JRadioButton();
        useEntropyRadioButton = new javax.swing.JRadioButton();
        separator = new javax.swing.JSeparator();
        suppressionWeightPerVariableLabel = new javax.swing.JLabel();
        suppressionWeightScrollPane = new javax.swing.JScrollPane();
        suppressionWeightList = new javax.swing.JList();
        suppressionWeightSlider = new javax.swing.JSlider();
        hhIdentifierPanel = new javax.swing.JPanel();
        keepInSafeFileRadioButton = new javax.swing.JRadioButton();
        changeIntoSequenceNumberRadioButton = new javax.swing.JRadioButton();
        removeFromSafeFileRadioButton = new javax.swing.JRadioButton();
        writeRecordRandomOrderCheckBox = new javax.swing.JCheckBox();
        progressbar = new javax.swing.JProgressBar();
        cancelButton = new javax.swing.JButton();
        makeFileButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Make Protected File");

        suppressionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Suppression"));

        suppressionButtonGroup.add(noSuppressionRadioButton);
        noSuppressionRadioButton.setText("No suppression");
        noSuppressionRadioButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                noSuppressionRadioButtonStateChanged(evt);
            }
        });

        suppressionButtonGroup.add(useWeightRadioButton);
        useWeightRadioButton.setText("Use weights");
        useWeightRadioButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                useWeightRadioButtonStateChanged(evt);
            }
        });

        suppressionButtonGroup.add(useEntropyRadioButton);
        useEntropyRadioButton.setSelected(true);
        useEntropyRadioButton.setText("Use entropy");
        useEntropyRadioButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                useEntropyRadioButtonStateChanged(evt);
            }
        });

        suppressionWeightPerVariableLabel.setText("Suppression weight per variable");

        suppressionWeightList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        suppressionWeightScrollPane.setViewportView(suppressionWeightList);

        suppressionWeightSlider.setMajorTickSpacing(100);
        suppressionWeightSlider.setMinorTickSpacing(5);
        suppressionWeightSlider.setPaintTicks(true);
        suppressionWeightSlider.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                suppressionWeightSliderCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        javax.swing.GroupLayout suppressionPanelLayout = new javax.swing.GroupLayout(suppressionPanel);
        suppressionPanel.setLayout(suppressionPanelLayout);
        suppressionPanelLayout.setHorizontalGroup(
            suppressionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separator)
            .addGroup(suppressionPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(suppressionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(suppressionWeightScrollPane)
                    .addComponent(noSuppressionRadioButton, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(useWeightRadioButton, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(useEntropyRadioButton, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(suppressionWeightPerVariableLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(suppressionWeightSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        suppressionPanelLayout.setVerticalGroup(
            suppressionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(suppressionPanelLayout.createSequentialGroup()
                .addComponent(noSuppressionRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(useWeightRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(useEntropyRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(suppressionWeightPerVariableLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(suppressionWeightScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(suppressionWeightSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        hhIdentifierPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("HH Identifier"));

        hhIdentifierButtonGroup.add(keepInSafeFileRadioButton);
        keepInSafeFileRadioButton.setSelected(true);
        keepInSafeFileRadioButton.setText("Keep in safe file");
        keepInSafeFileRadioButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                keepInSafeFileRadioButtonStateChanged(evt);
            }
        });

        hhIdentifierButtonGroup.add(changeIntoSequenceNumberRadioButton);
        changeIntoSequenceNumberRadioButton.setText("Change into sequence number");
        changeIntoSequenceNumberRadioButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                changeIntoSequenceNumberRadioButtonStateChanged(evt);
            }
        });

        hhIdentifierButtonGroup.add(removeFromSafeFileRadioButton);
        removeFromSafeFileRadioButton.setText("Remove from safe file");
        removeFromSafeFileRadioButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                removeFromSafeFileRadioButtonStateChanged(evt);
            }
        });

        javax.swing.GroupLayout hhIdentifierPanelLayout = new javax.swing.GroupLayout(hhIdentifierPanel);
        hhIdentifierPanel.setLayout(hhIdentifierPanelLayout);
        hhIdentifierPanelLayout.setHorizontalGroup(
            hhIdentifierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hhIdentifierPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hhIdentifierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(keepInSafeFileRadioButton)
                    .addComponent(changeIntoSequenceNumberRadioButton)
                    .addComponent(removeFromSafeFileRadioButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hhIdentifierPanelLayout.setVerticalGroup(
            hhIdentifierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hhIdentifierPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(keepInSafeFileRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(changeIntoSequenceNumberRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeFromSafeFileRadioButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        writeRecordRandomOrderCheckBox.setText("Write records in random order");
        writeRecordRandomOrderCheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                writeRecordRandomOrderCheckBoxStateChanged(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        makeFileButton.setText("Make file");
        makeFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeFileButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(suppressionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hhIdentifierPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(writeRecordRandomOrderCheckBox)
                            .addComponent(progressbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(makeFileButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(suppressionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hhIdentifierPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(writeRecordRandomOrderCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(progressbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancelButton)
                            .addComponent(makeFileButton))
                        .addGap(17, 17, 17))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void makeFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeFileButtonActionPerformed
        controller.makeFile();
    }//GEN-LAST:event_makeFileButtonActionPerformed

    private void noSuppressionRadioButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_noSuppressionRadioButtonStateChanged
        controller.noSuppression();
    }//GEN-LAST:event_noSuppressionRadioButtonStateChanged

    private void useWeightRadioButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_useWeightRadioButtonStateChanged
        controller.useWeight();
    }//GEN-LAST:event_useWeightRadioButtonStateChanged

    private void useEntropyRadioButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_useEntropyRadioButtonStateChanged
        controller.useEntropy();
    }//GEN-LAST:event_useEntropyRadioButtonStateChanged

    private void keepInSafeFileRadioButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_keepInSafeFileRadioButtonStateChanged
        controller.keepInSafeFile();
    }//GEN-LAST:event_keepInSafeFileRadioButtonStateChanged

    private void changeIntoSequenceNumberRadioButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_changeIntoSequenceNumberRadioButtonStateChanged
        controller.changeIntoSequenceNumber();
    }//GEN-LAST:event_changeIntoSequenceNumberRadioButtonStateChanged

    private void removeFromSafeFileRadioButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_removeFromSafeFileRadioButtonStateChanged
        controller.removeFromSafeFile();
    }//GEN-LAST:event_removeFromSafeFileRadioButtonStateChanged

    private void writeRecordRandomOrderCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_writeRecordRandomOrderCheckBoxStateChanged
        controller.writeRecordRandomOrder();
    }//GEN-LAST:event_writeRecordRandomOrderCheckBoxStateChanged

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        controller.cancel();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void suppressionWeightSliderCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_suppressionWeightSliderCaretPositionChanged
        controller.suppressionWeight();
    }//GEN-LAST:event_suppressionWeightSliderCaretPositionChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MakeProtectedFileView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MakeProtectedFileView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MakeProtectedFileView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MakeProtectedFileView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MakeProtectedFileView view = new MakeProtectedFileView(new javax.swing.JFrame(), true);
                view.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                view.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JRadioButton changeIntoSequenceNumberRadioButton;
    private javax.swing.ButtonGroup hhIdentifierButtonGroup;
    private javax.swing.JPanel hhIdentifierPanel;
    private javax.swing.JRadioButton keepInSafeFileRadioButton;
    private javax.swing.JButton makeFileButton;
    private javax.swing.JRadioButton noSuppressionRadioButton;
    private javax.swing.JProgressBar progressbar;
    private javax.swing.JRadioButton removeFromSafeFileRadioButton;
    private javax.swing.JSeparator separator;
    private javax.swing.ButtonGroup suppressionButtonGroup;
    private javax.swing.JPanel suppressionPanel;
    private javax.swing.JList suppressionWeightList;
    private javax.swing.JLabel suppressionWeightPerVariableLabel;
    private javax.swing.JScrollPane suppressionWeightScrollPane;
    private javax.swing.JSlider suppressionWeightSlider;
    private javax.swing.JRadioButton useEntropyRadioButton;
    private javax.swing.JRadioButton useWeightRadioButton;
    private javax.swing.JCheckBox writeRecordRandomOrderCheckBox;
    // End of variables declaration//GEN-END:variables
}
